services:
  mongodb:
    image: mongo:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        max_attempts: 0
      placement:
        constraints:
          - node.role == manager
          - node.labels.manager == 00
    expose:
      - 27017
    volumes:
      - /mnt/gluster/managers/containers/swirl-dev/mongo:/data/db
    networks:
      - internal

  manager_agent:
    image: cuigh/socat:latest
    deploy:
      mode: global
      restart_policy:
        condition: any
        max_attempts: 0
      placement:
        constraints:
          - node.role == manager
      endpoint_mode: dnsrr
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - internal
    depends_on:
      - mongodb

  worker_agent:
    image: cuigh/socat:latest
    deploy:
      mode: global
      restart_policy:
        condition: any
        max_attempts: 0
      placement:
        constraints:
          - node.role == worker
      endpoint_mode: dnsrr
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - internal
    depends_on:
      - mongodb

  swirl:
    image: registry.example.com:443/cuigh/swirl:0.8.6
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        max_attempts: 0
      placement:
        constraints:
          - node.role == manager
          - node.labels.manager == 00
      labels:
        com.centurylinklabs.watchtower.enable: "true"
        traefik.enable: "true"
        traefik.http.routers.swirl.entrypoints: "https"
        traefik.http.routers.swirl.middlewares: "internalnet@file"
        traefik.http.routers.swirl.rule: "Host(`swirl-dkrdev.example.com`)"
        traefik.http.routers.swirl.tls: "true"
        traefik.http.services.swirl.loadbalancer.passHostHeader: "true"
        traefik.http.services.swirl.loadbalancer.server.port: "8001"
        # Abilita le sticky sessions
        traefik.http.services.swirl.loadbalancer.sticky.cookie: "true"
        # Opzionale: dai un nome al cookie per debuggarlo meglio
        traefik.http.services.swirl.loadbalancer.sticky.cookie.name: "sticky_dkrdev"
        # Se usi HTTPS (consigliato in produzione)
        traefik.http.services.swirl.loadbalancer.sticky.cookie.secure: "true"
    ports:
      - "8001:8001"
    environment:
      # USA i nomi reali dei servizi (stack prefissato)
      - AGENTS=swirl-dev_manager_agent,swirl-dev_worker_agent
      - DB_ADDRESS=mongodb://mongodb:27017/swirl
      - DOCKER_ENDPOINT=tcp://manager_agent:2375
      - SWIRL_BACKUP_KEY=${SWIRL_BACKUP_KEY}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/gluster/managers/containers/swirl-dev/data:/data/swirl
    networks:
      - internal
      - traefik-net
      - egress
    depends_on:
      - worker_agent
      - manager_agent

networks:
  internal:
  traefik-net:
    external: true
  egress:
    external: true
    