package docker

import (
	"bytes"
	"context"
	"io"
	"strconv"
	"strings"

	"github.com/cuigh/swirl/misc"
	"github.com/docker/docker/api/types"
	"github.com/docker/docker/api/types/container"
	"github.com/docker/docker/api/types/filters"
	"github.com/docker/docker/client"
	"github.com/docker/docker/pkg/stdcopy"
)

// ContainerCount returns the number of containers (all states) on the given host.
func (d *Docker) ContainerCount(ctx context.Context, node string) (count int, err error) {
	c, err := d.agent(node)
	if err != nil {
		return 0, err
	}
	list, err := c.ContainerList(ctx, container.ListOptions{All: true})
	if err != nil {
		return 0, err
	}
	return len(list), nil
}

// ContainerListAll returns all containers (any state) on the given host.
// Used by higher layers to compute image reference counts, etc.
func (d *Docker) ContainerListAll(ctx context.Context, node string) ([]container.Summary, error) {
	c, err := d.agent(node)
	if err != nil {
		return nil, err
	}
	return c.ContainerList(ctx, container.ListOptions{All: true})
}

// ContainerList return containers on the host.
func (d *Docker) ContainerList(ctx context.Context, node, name, status, project string, pageIndex, pageSize int) (containers []container.Summary, total int, err error) {
	var c *client.Client
	c, err = d.agent(node)
	if err != nil {
		return
	}

	opts := container.ListOptions{Filters: filters.NewArgs()}
	if status == "" {
		opts.All = true
	} else {
		opts.Filters.Add("status", status)
	}
	if name != "" {
		opts.Filters.Add("name", name)
	}
	if project != "" {
		opts.Filters.Add("label", "com.docker.compose.project="+project)
	}

	containers, err = c.ContainerList(ctx, opts)
	if err == nil {
		total = len(containers)
		start, end := misc.Page(total, pageIndex, pageSize)
		containers = containers[start:end]
	}
	return
}

// ContainerInspect return container raw information.
func (d *Docker) ContainerInspect(ctx context.Context, node, id string) (ctr container.InspectResponse, raw []byte, err error) {
	var c *client.Client
	if c, err = d.agent(node); err == nil {
		ctr, raw, err = c.ContainerInspectWithRaw(ctx, id, true)
	}
	return
}

// ContainerRemove remove a container.
//
// `removeAnonymousVolumes` maps to `RemoveOptions.RemoveVolumes` on the Docker
// SDK: when true, *anonymous* volumes declared by the container (e.g. VOLUME
// directives baked into the image) are deleted together with the container.
// Named volumes are NEVER removed by this flag — that's consistent with the
// `docker rm -v` CLI semantics and intentional: named volumes are managed
// separately (e.g. compose stack removal).
func (d *Docker) ContainerRemove(ctx context.Context, node, id string, removeAnonymousVolumes bool) (err error) {
	var c *client.Client
	if c, err = d.agent(node); err == nil {
		err = c.ContainerRemove(ctx, id, container.RemoveOptions{RemoveVolumes: removeAnonymousVolumes})
	}
	return
}

// ContainerExecCreate creates an exec instance.
func (d *Docker) ContainerExecCreate(ctx context.Context, node, id string, cmd string) (resp container.ExecCreateResponse, err error) {
	var c *client.Client
	c, err = d.agent(node)
	if err != nil {
		return
	}

	opts := container.ExecOptions{
		AttachStdin:  true,
		AttachStdout: true,
		AttachStderr: true,
		Tty:          true,
		Cmd:          strings.Split(cmd, " "),
	}
	resp, err = c.ContainerExecCreate(ctx, id, opts)
	return
}

// ContainerExecAttach attaches a connection to an exec process in the server.
func (d *Docker) ContainerExecAttach(ctx context.Context, node, id string) (resp types.HijackedResponse, err error) {
	var c *client.Client
	c, err = d.agent(node)
	if err != nil {
		return
	}

	opts := container.ExecStartOptions{
		Detach: false,
		Tty:    true,
	}
	resp, err = c.ContainerExecAttach(ctx, id, opts)
	return
}

// ContainerExecStart starts an exec instance.
func (d *Docker) ContainerExecStart(ctx context.Context, node, id string) (err error) {
	c, err := d.agent(node)
	if err != nil {
		return err
	}

	opts := container.ExecStartOptions{
		Detach: false,
		Tty:    true,
	}
	return c.ContainerExecStart(ctx, id, opts)
}

// ContainerLogs returns the logs generated by a container.
func (d *Docker) ContainerLogs(ctx context.Context, node, id string, lines int, timestamps bool) (stdout, stderr *bytes.Buffer, err error) {
	var c *client.Client
	c, err = d.agent(node)
	if err != nil {
		return
	}

	var (
		rc   io.ReadCloser
		opts = container.LogsOptions{
			ShowStdout: true,
			ShowStderr: true,
			Tail:       strconv.Itoa(lines),
			Timestamps: timestamps,
		}
	)
	if rc, err = c.ContainerLogs(ctx, id, opts); err == nil {
		defer rc.Close()

		stdout = &bytes.Buffer{}
		stderr = &bytes.Buffer{}
		_, err = stdcopy.StdCopy(stdout, stderr, rc)
	}
	return
}

// ContainerPrune remove all unused containers.
func (d *Docker) ContainerPrune(ctx context.Context, node string) (report container.PruneReport, err error) {
	var c *client.Client
	if c, err = d.agent(node); err == nil {
		report, err = c.ContainersPrune(ctx, filters.NewArgs())
	}
	return
}

// ContainerStart starts a container.
func (d *Docker) ContainerStart(ctx context.Context, node, id string) (err error) {
	var c *client.Client
	if c, err = d.agent(node); err == nil {
		err = c.ContainerStart(ctx, id, container.StartOptions{})
	}
	return
}

// ContainerStop stops a running container.
// If timeoutSecs is zero or negative, Docker's default (10s) is used.
func (d *Docker) ContainerStop(ctx context.Context, node, id string, timeoutSecs int) (err error) {
	var c *client.Client
	if c, err = d.agent(node); err == nil {
		opts := container.StopOptions{}
		if timeoutSecs > 0 {
			opts.Timeout = &timeoutSecs
		}
		err = c.ContainerStop(ctx, id, opts)
	}
	return
}

// ContainerRestart restarts a container.
func (d *Docker) ContainerRestart(ctx context.Context, node, id string, timeoutSecs int) (err error) {
	var c *client.Client
	if c, err = d.agent(node); err == nil {
		opts := container.StopOptions{}
		if timeoutSecs > 0 {
			opts.Timeout = &timeoutSecs
		}
		err = c.ContainerRestart(ctx, id, opts)
	}
	return
}

// ContainerKill kills a container with the given signal (e.g. "SIGKILL").
// If signal is empty, Docker's default (SIGKILL) is used.
func (d *Docker) ContainerKill(ctx context.Context, node, id, signal string) (err error) {
	var c *client.Client
	if c, err = d.agent(node); err == nil {
		err = c.ContainerKill(ctx, id, signal)
	}
	return
}

// ContainerPause pauses a container.
func (d *Docker) ContainerPause(ctx context.Context, node, id string) (err error) {
	var c *client.Client
	if c, err = d.agent(node); err == nil {
		err = c.ContainerPause(ctx, id)
	}
	return
}

// ContainerUnpause unpauses a paused container.
func (d *Docker) ContainerUnpause(ctx context.Context, node, id string) (err error) {
	var c *client.Client
	if c, err = d.agent(node); err == nil {
		err = c.ContainerUnpause(ctx, id)
	}
	return
}

// ContainerRename renames a container.
func (d *Docker) ContainerRename(ctx context.Context, node, id, newName string) (err error) {
	var c *client.Client
	if c, err = d.agent(node); err == nil {
		err = c.ContainerRename(ctx, id, newName)
	}
	return
}

// ContainerStats returns a one-shot stats snapshot for a container.
func (d *Docker) ContainerStats(ctx context.Context, node, id string) (raw []byte, err error) {
	var c *client.Client
	if c, err = d.agent(node); err != nil {
		return
	}
	resp, err := c.ContainerStatsOneShot(ctx, id)
	if err != nil {
		return
	}
	defer resp.Body.Close()
	buf := &bytes.Buffer{}
	if _, err = io.Copy(buf, resp.Body); err != nil {
		return
	}
	raw = buf.Bytes()
	return
}
